spring:
  profiles:
    active: local
  application:
    name: Gym App User Profile Service
---
spring:
  config:
    activate:
      on-profile: local
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE}
      max-request-size: ${MAX_FILE_SIZE}

  datasource:
    url: jdbc:postgresql://localhost:5432/gym_app_db
    username: gym_app_user
    password: gym_app_pass
    hikari:
      auto-commit: false

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    liquibase-schema: public

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false

  springdoc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui.html

  management:
    endpoints:
      web:
        exposure:
          include: health

  kafka:
    aggregation:
      like-notification:
        interval-minutes: 1440
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.UUIDDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: gym-app-listener-group
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.UUIDSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    topics:
      account-register: "userProfile.create-account"
      likes-events: "workout.like-events"
      likes-notifications: "userProfile.notifications-likes-dislikes"
    streams:
      application-id: gym-app-backend-streams-single-broker
      properties:
        default.key.serde: org.apache.kafka.common.serialization.Serdes$UUIDSerde
        default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde

aws:
  s3:
    region: ${AWS_REGION}
    bucket: ${AWS_BUCKET}
    access:
      key: ${AWS_ACCESS_KEY}
    secret:
      key: ${AWS_SECRET_KEY}

logging:
  level:
    kafka: WARN
    org.springframework.kafka: WARN
    org.apache.kafka: WARN
    org.apache.kafka.clients: WARN
    org.apache.kafka.streams: WARN