spring:
  application:
    name: gym-app-gateway-service
  config:
    activate:
      on-profile:
        - local
        - deployment
    import: configserver:${CONFIG_SERVER_URI:http://localhost:8888}