spring:
  application:
    name: gym-app-gateway-service
  config:
    activate:
      on-profile: local
    import: configserver:${CONFIG_SERVER_URI:http://localhost:8888}

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${AUTH_SERVICE_URL:http://localhost:8080}/.well-known/jwks.json
          issuer-uri: ${AUTH_SERVICE_URL:http://localhost:8080}

logging:
  level:
    org:
      springframework:
        security: DEBUG
