apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  labels:
    app: gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: gateway-deployment
      app: gym-app-microservices
  template:
    metadata:
      labels:
        app: gym-app-microservices
        name: gateway-pod
    spec:
      containers:
        - name: gateway
          image: sourcerygraduates/gymapp-gateway:jib
          ports:
            - containerPort: 8080