spring:
  application:
    name: config-server
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: "git@github.com:Sourcery-Graduates/GymAppConfig.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
          basedir: ./configRepo
          ignore-local-ssh-settings: ${IGNORE_LOCAL_SSH_SETTINGS:false}
          private-key: ${SSH_PRIVATE_KEY:}
server:
  port: 8888