apiVersion: v1
kind: Pod
metadata:
  name: pgadmin-pod
  labels:
    app: gym-app-microservices
    name: pgadmin-pod
spec:
  containers:
    - name: pgadmin
      image: dpage/pgadmin4
      env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: admin@admin.com
        - name: PGADMIN_DEFAULT_PASSWORD
          value: admin_pass
      ports:
        - containerPort: 80
          hostPort: 8000
