apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-deployment
  labels:
    app: gym-app-microservices
    name: email-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gym-app-microservices
      name: email-pod
  template:
    metadata:
      labels:
        app: gym-app-microservices
        name: email-pod
    spec:
      containers:
        - name: email
          image: sourcerygraduates/gymapp-email:jib
          ports:
            - containerPort: 8084
          env:
            - name: CONFIG_SERVER_URI
              value: http://configserver-service:8888
---
apiVersion: v1
kind: Service
metadata:
  name: email-service
  labels:
    name: email-service
    app: gym-app-microservices
spec:
  type: ClusterIP
  ports:
    - port: 8084
      targetPort: 8084
  selector:
    app: gym-app-microservices
    name: email-pod