apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin-deployment
  labels:
    app: gym-app-microservices
    name: pgadmin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gym-app-microservices
      name: pgadmin-pod
  template:
    metadata:
      labels:
        app: gym-app-microservices
        name: pgadmin-pod
    spec:
      containers:
        - name: pgadmin
          image: dpage/pgadmin4
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: admin@admin.com
            - name: PGADMIN_DEFAULT_PASSWORD
              value: admin_pass
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  labels:
    name: pgadmin-service
    app: gym-app-microservices
spec:
  type: NodePort
  selector:
    app: gym-app-microservices
    name: pgadmin-pod
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005
